FROM golang:latest AS builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o stress-test .

FROM alpine:latest
COPY --from=builder /app/stress-test .
ENTRYPOINT  ["./stress-test", "run"]